import { site, navigation, stages, programs, faqs } from './content.mjs';

export const escape = value => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const arrow = '<span aria-hidden="true">↗</span>';
const link = (href, text, className = 'text-link') => `<a class="${className}" href="${escape(href)}">${escape(text)} ${arrow}</a>`;
const badge = label => `<span class="eyebrow">${escape(label)}</span>`;
const draft = text => site.preview ? `<p class="content-note"><span>Preview note</span> ${escape(text)}</p>` : '';
const photo = (className = '', priority = false) => `<figure class="chess-photo ${className}"><img src="${escape(site.photo)}" alt="Wooden chess pieces arranged on a chessboard in natural light" width="1260" height="840" ${priority ? 'fetchpriority="high"' : 'loading="lazy"'}><figcaption>Chess study · illustrative photograph</figcaption></figure>`;
const wa = () => `https://wa.me/${site.whatsapp}?text=${encodeURIComponent('Hello NX Chess, I would like to know more about your lessons and curriculum.')}`;
const motionControl = () => '<button class="motion-control" data-motion-toggle hidden>Pause motion</button>';
const boardAtmosphere = () => '<div class="board-atmosphere" aria-hidden="true"><span>♘</span><span>♙</span></div>';
const brand = () => `<a class="brand" href="/" aria-label="NX Chess home"><span class="brand-mark" aria-hidden="true">♘</span><span>NX<span class="brand-light">CHESS</span><small>CHESS TEACHING CENTER</small></span></a>`;

function header(path) {
  return `<a class="skip-link" href="#main">Skip to content</a>${site.preview ? '<div class="preview-bar">Website preview <span>Programs &amp; teaching details are awaiting confirmation.</span></div>' : ''}<header class="site-header"><div class="container header-inner">${brand()}<button class="menu-toggle" data-menu-toggle aria-expanded="false" aria-controls="primary-navigation">Menu</button><nav id="primary-navigation" aria-label="Main navigation" data-navigation>${navigation.map(([href, title]) => `<a href="${href}" ${path === href ? 'aria-current="page"' : ''} class="${href === '/contact/' ? 'nav-contact' : ''}">${title}${href === '/contact/' ? ' <span aria-hidden="true">↗</span>' : ''}</a>`).join('')}</nav></div></header>`;
}

function footer() {
  return `<footer class="site-footer"><div class="container footer-grid"><div class="footer-intro">${brand()}<p>A thoughtful next move<br>starts with a little curiosity.</p></div><div><h2>Explore</h2>${link('/', 'Home')}${link('/about/', 'About NX Chess')}${link('/coaches/', 'Coaches')}</div><div><h2>Learn</h2>${link('/programs/', 'Programs')}${link('/curriculum/', 'Curriculum')}${link('/faq/', 'FAQs')}</div><div><h2>Let’s talk</h2>${site.contactConfirmed ? `<a href="${escape(wa())}" data-whatsapp>WhatsApp ${arrow}</a><a href="tel:${site.phone}">${site.phoneDisplay}</a>` : link('/contact/', 'Contact information')}${link('/contact/', 'Contact us')}</div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} NX Chess</span><span>Learn. Think. Play.</span><a href="${site.photoSource}">Photo: Pixabay / Pexels</a></div></footer>`;
}

function invite(title = 'Your next move starts here.', description = 'Ask about the curriculum, explore your starting point, or simply say hello.') {
  return `<section class="invitation"><div class="container invite-inner"><div>${badge('LET’S TALK CHESS')}<h2>${title}</h2><p>${description}</p></div>${link('/contact/', 'Talk to NX Chess', 'button button-cream')}</div></section>`;
}

function intro(label, title, description) {
  return `<section class="page-intro container">${boardAtmosphere()}${motionControl()}<div class="breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>${escape(label)}</span></div>${badge(label)}<h1>${title}</h1><p class="lead">${description}</p></section>`;
}

function programCards() {
  return `<div class="program-grid">${programs.map((program, index) => `<article class="program-card"><div class="program-top"><span class="piece" aria-hidden="true">${program.icon}</span><span class="small-label">${program.range}</span></div><p class="kicker">${program.label}</p><h3>${program.name}</h3><p>${program.description}</p>${link(`/programs/#${program.id}`, 'Explore this pathway')}<span class="card-index" aria-hidden="true">0${index + 1}</span></article>`).join('')}</div>`;
}

function questions(items = faqs) {
  return `<div class="questions">${items.map(item => `<details><summary>${escape(item.question)}<span class="question-toggle" aria-hidden="true"></span></summary><div class="answer"><p>${escape(item.answer)}</p>${item.link ? link(...item.link) : ''}</div></details>`).join('')}</div>`;
}

function learningHabits() {
  return `<section class="learning-habits section"><div class="container"><div class="section-heading"><div>${badge('WHAT YOU PRACTICE AT THE BOARD')}<h2>A thoughtful game.<br>A chance to think differently.</h2></div><p>Every position offers something to notice, compare, or explain. These are habits to practice in chess, not promises about grades or ratings.</p></div><div class="habits-grid">${[['Look carefully', 'Notice the pieces, the threats, and what changed with the last move.', '♙'], ['Consider alternatives', 'Compare a few possible moves before choosing one.', '♘'], ['Think a step ahead', 'Imagine the opponent’s reply and check your idea again.', '♗'], ['Explain your choice', 'Put your reasoning into words, then revisit it after the game.', '♖']].map(([title, body, piece]) => `<article><span class="piece" aria-hidden="true">${piece}</span><h3>${title}</h3><p>${body}</p></article>`).join('')}</div></div></section>`;
}

function gettingStarted() {
  return `<section class="container section getting-started"><div class="section-heading"><div>${badge('FROM A QUESTION TO A STARTING POINT')}<h2>Begin with<br>a conversation.</h2></div><p>For learners and families exploring chess, the first step can be simple.</p></div><div class="value-grid">${[['Tell us where you are', 'Share your chess experience and what interests you.'], ['Ask the practical questions', 'Discuss lesson formats, suitable levels, and current availability.'], ['Choose the next step', 'Explore the curriculum and agree on a starting point with the team.']].map(([title, body], i) => `<article><span class="eyebrow">0${i + 1}</span><h3>${title}</h3><p>${body}</p></article>`).join('')}</div><div class="inquiry-options"><p>Interested in a particular format? Ask what is currently available.</p><div>${['Private coaching', 'School groups', 'Tournament preparation'].map(topic => link('/contact/?program=' + encodeURIComponent(topic), 'Ask about ' + topic.toLowerCase())).join('')}</div><small>Inquiry topics only; these services are not yet confirmed.</small></div></section>`;
}

function home() {
  return `<section class="container hero">${boardAtmosphere()}<div class="hero-copy">${badge('A PLACE TO THINK. A PLACE TO GROW.')}<h1>Every great move<br>starts with<br><em>understanding.</em></h1><p class="lead">Discover the ideas behind the moves.<br>Explore a thoughtful approach to learning chess, one step at a time.</p><div class="hero-actions">${link('/programs/', 'Explore our programs', 'button')}${link('/contact/', 'Talk to us')}</div><div class="hero-note"><span class="note-line"></span><p>From your first move<br>to a more considered game.</p></div></div><div class="hero-visual">${motionControl()}${photo('hero-photo', true)}<div class="image-label"><span class="piece" aria-hidden="true">♘</span><div><strong>A game worth understanding.</strong><span>Curiosity belongs at the board.</span></div></div><span class="vertical-note" aria-hidden="true">NX CHESS — THE ART OF LEARNING</span></div></section>
  <div class="principles-strip"><div class="container"><span>Understand the idea</span><i aria-hidden="true">✦</i><span>Try it on the board</span><i aria-hidden="true">✦</i><span>Reflect &amp; improve</span></div></div>
  <section class="section container"><div class="section-heading"><div>${badge('FIND YOUR STARTING POINT')}<h2>A little curiosity.<br>A world of possibilities.</h2></div><div><p>Different starting points, connected by the same idea: understand a little more with every game.</p>${link('/programs/', 'View all programs')}</div></div>${draft('These learning pathways are proposed. Ask us about current programs and availability.')}${programCards()}</section>
  <section class="approach-section"><div class="container approach-grid"><div class="large-quote">${badge('THE WAY WE THINK ABOUT CHESS')}<h2>More than<br>the right move.<br><em>The reason<br>behind it.</em></h2>${link('/about/', 'Get to know NX Chess')}</div><div class="approach-steps">${[['01', 'Understand', 'Begin with a clear idea. Explore what a piece can do, what a position asks, and why a move matters.'], ['02', 'Practice', 'Bring the idea onto the board. Try a position, consider another move, and give yourself space to think.'], ['03', 'Reflect', 'Look back with curiosity. Notice one useful lesson and carry it into the next game.']].map(([n, title, body]) => `<article><span>${n}</span><div><h3>${title}</h3><p>${body}</p></div></article>`).join('')}</div></div></section>
  <section class="section container"><div class="section-heading"><div>${badge('THE LEARNING JOURNEY')}<h2>Small steps.<br>Deeper understanding.</h2></div><div><p>Explore a proposed path from the basic rules to more purposeful play.</p>${link('/curriculum/', 'See the full curriculum')}</div></div><ol class="stage-preview">${stages.map((stage, i) => `<li><a href="/curriculum/#${stage.id}"><span class="stage-number">0${i + 1}</span><h3>${stage.name}</h3><p>${stage.short}</p><span class="stage-arrow" aria-hidden="true">↗</span></a></li>`).join('')}</ol></section>
  ${learningHabits()}
  <section class="container coach-teaser"><div class="coach-art" aria-hidden="true"><span>♔</span><span>♘</span><small>LEARNING IS A CONVERSATION.</small></div><div>${badge('THE PEOPLE BEHIND THE BOARD')}<h2>Good questions.<br>Patient guidance.</h2><p>Meet the people behind NX Chess and explore the thinking that shapes the learning experience.</p>${site.coaches.length ? '' : draft('Coach introductions will be added once names and biographies are confirmed.')}${link('/coaches/', 'Meet the coaches')}</div></section>
  <section class="section container faq-preview"><div>${badge('A FEW THINGS YOU MIGHT BE WONDERING')}<h2>Let’s make<br>the first step easier.</h2>${link('/faq/', 'All questions & answers')}</div>${questions(faqs.slice(0, 2))}</section>${invite()}`;
}

function programsPage() {
  return `${intro('Programs', 'Find your way<br><em>into the game.</em>', 'Explore learning pathways built around understanding. Start with the basics, look deeper into positions, or bring your ideas together through review.')}
  <section class="container programs-body">${draft('These are proposed learning pathways, not confirmed class offerings. Formats, age groups, schedules, and fees are available by inquiry.')}<div class="program-jumps">${programs.map(p => link('#' + p.id, p.name)).join('')}</div>${programs.map((p, i) => `<article class="program-detail" id="${p.id}"><div class="program-emblem emblem-${i}"><span aria-hidden="true">${p.icon}</span><small>${p.range}</small></div><div><span class="eyebrow">0${i + 1} / ${p.label}</span><h2>${p.name}</h2><p class="lead">${p.description}</p><dl class="program-facts"><div><dt>Starting point</dt><dd>${p.audience}</dd></div><div><dt>Learning focus</dt><dd>${p.focus}</dd></div></dl><div class="actions">${link('/contact/?program=' + encodeURIComponent(p.name), 'Ask about this pathway', 'button')}${link('/curriculum/#' + p.stage, 'Related curriculum')}</div></div></article>`).join('')}</section><section class="container section compact"><div class="split-note"><h2>Not sure where<br>you belong?</h2><p>You don’t have to choose a pathway before getting in touch. A little about your experience and what interests you is a good place to start.</p></div></section>${gettingStarted()}${invite('A conversation is a good first move.')}`;
}

function curriculumPage() {
  return `${intro('Curriculum', 'A clear path.<br><em>One thoughtful step at a time.</em>', 'From knowing how the pieces move to understanding what a position needs. Explore the ideas, practice, and purpose behind each stage.')}
  <section class="container curriculum-body">${draft('This curriculum is proposed and awaiting confirmation. Stages describe learning progression, not a guaranteed timeline or rating result.')}<div class="curriculum-layout"><aside><p class="eyebrow">THE FIVE STAGES</p><nav aria-label="Curriculum stages">${stages.map((stage, i) => `<a href="#${stage.id}"><span>0${i + 1}</span>${stage.name}</a>`).join('')}</nav><p>Read at your own pace.<br>No account needed.</p></aside><div>${stages.map((stage, i) => `<article class="curriculum-stage" id="${stage.id}"><div class="stage-title"><span class="stage-number">0${i + 1}</span><div><p class="kicker">${stage.for}</p><h2>${stage.name}</h2></div><span class="piece" aria-hidden="true">${stage.icon}</span></div><p class="stage-tagline">${stage.short}</p><div class="stage-columns"><div><h3>What you’ll explore</h3><ul>${stage.topics.map(t => `<li>${t}</li>`).join('')}</ul></div><div><h3>What understanding looks like</h3><ul>${stage.outcomes.map(t => `<li>${t}</li>`).join('')}</ul></div></div><div class="practice"><span class="eyebrow">ON THE BOARD</span><p>${stage.practice}</p></div>${link('/contact/?program=' + encodeURIComponent(stage.name), 'Ask about this stage')}</article>`).join('')}</div></div></section>${invite('Where will your first move take you?', 'Tell us what you already know and what you would like to explore next.')}`;
}

function coachesPage() {
  const profiles = site.coaches.length ? site.coaches.map(coach => `<article class="coach-profile"><h2>${escape(coach.name)}</h2><p class="kicker">${escape(coach.role)}</p><p>${escape(coach.bio)}</p></article>`).join('') : `<div class="profile-notice"><span class="piece" aria-hidden="true">♘</span><div><span class="eyebrow">MEET THE PEOPLE</span><h2>Introductions<br>are on their way.</h2><p>We’re preparing the coach profiles for this website. In the meantime, ask NX Chess about the people and approach behind the teaching.</p>${link('/contact/?program=Coaches', 'Ask about our coaches', 'button')}</div></div>`;
  return `${intro('Coaches', 'There’s a person<br><em>behind every lesson.</em>', 'A thoughtful question. A fresh way of looking at a position. Space to try again. Explore the people and approach behind NX Chess.')}<section class="container">${profiles}</section><section class="section container"><div class="section-heading"><div>${badge('A TEACHING PHILOSOPHY TO EXPLORE')}<h2>Guidance that makes<br>room for thinking.</h2></div><p>Our proposed teaching approach puts explanation, practice, and reflection at the center of the lesson.</p></div><div class="value-grid">${[['Clear explanations', 'The reason behind a move is worth taking time to understand.'], ['Space for questions', 'A question can open up a useful new way to look at a position.'], ['Thoughtful reflection', 'A played game offers ideas to revisit, discuss, and practice.']].map(([title, text], i) => `<article><span class="eyebrow">0${i + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>${invite('Ask us about the teaching.', 'We’re happy to hear what you’re hoping to learn.')}`;
}

function aboutPage() {
  return `${intro('About NX Chess', 'A place for chess.<br><em>And the curiosity it brings.</em>', 'NX Chess is a chess teaching center. This website brings its learning pathways, curriculum, and contact information together in one welcoming place.')}<section class="container about-feature">${photo()}<div>${badge('THE IDEA AT THE HEART OF IT')}<h2>Learn the move.<br>Understand the why.</h2><p>Chess offers a reason to slow down, look carefully, and consider another possibility. That is the spirit behind this proposed learning experience.</p><p>From the first rules to a more considered game, the path is built around explaining ideas and putting them into practice.</p>${link('/curriculum/', 'Explore the learning path')}</div></section><section class="section container"><div class="story-note"><span class="eyebrow">OUR STORY</span><h2>The next chapter<br>is taking shape.</h2><p>The center’s full story, coach introductions, and lesson arrangements are being prepared for this website. We’ll share those details once they are confirmed.</p>${link('/contact/', 'Get in touch with NX Chess')}</div></section><section class="approach-section"><div class="container section"><div class="section-heading"><div>${badge('A PROPOSED LESSON RHYTHM')}<h2>Understand. Try. Reflect.</h2></div><p>Simple ideas that keep learning connected to the board.</p></div><div class="value-grid">${[['Start with an idea', 'Explore a rule, a pattern, or a decision in a position.'], ['Give it a try', 'Practice the idea and consider the opponent’s reply.'], ['Take something forward', 'Review a decision and find one thing to work on next.']].map(([title, text], i) => `<article><span class="eyebrow">0${i + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></div></section>${invite()}`;
}

function faqPage() {
  const groups = [...new Set(faqs.map(f => f.group))];
  return `${intro('FAQs', 'A few answers.<br><em>An easier first step.</em>', 'Find your way around the learning pathways and practical details. If your question isn’t here, a conversation is always a good place to start.')}<section class="container faq-page"><aside><p class="eyebrow">IN THIS SECTION</p>${groups.map((group, index) => link('#faq-' + index, group)).join('')}${link('/contact/', 'Ask another question', 'button')}</aside><div>${groups.map((group, i) => `<section id="faq-${i}" class="faq-group"><h2>${group}</h2>${questions(faqs.filter(f => f.group === group))}</section>`).join('')}</div></section>${invite('Still have a question?', 'Tell us what you would like to know about NX Chess.')}`;
}

function contactPage() {
  return `${intro('Contact us', 'Let’s talk<br><em>about your next move.</em>', 'Questions about the curriculum? Wondering where to begin? Tell us a little about your chess experience and what you would like to learn.')}<section class="container contact-layout"><div class="contact-card"><span class="eyebrow">A CONVERSATION STARTS HERE</span><h2>Say hello<br>on WhatsApp.</h2><p>Ask about learning pathways, coaches, or current lesson arrangements.</p><p class="inquiry-context" data-inquiry hidden></p>${site.contactConfirmed ? `<a class="contact-number" href="tel:${site.phone}">${site.phoneDisplay}</a><a class="button button-cream" href="${escape(wa())}" data-whatsapp>Message on WhatsApp ${arrow}</a><p class="contact-hint">Opens WhatsApp · You review the message before sending.</p>` : '<p>Contact details are awaiting confirmation.</p>'}</div><div class="contact-guide"><span class="eyebrow">NOT SURE WHAT TO SAY?</span><h2>A little about you<br>is a good start.</h2><ol><li><span>01</span><div><h3>Your experience</h3><p>Are you new to chess, playing casually, or returning to the board?</p></div></li><li><span>02</span><div><h3>Your interests</h3><p>Tell us what you would enjoy learning or understanding better.</p></div></li><li><span>03</span><div><h3>Your questions</h3><p>Ask about lesson formats, suitable programs, or availability.</p></div></li></ol><p class="privacy-note">Keep your first message simple. No documents or sensitive student details are needed.</p></div></section><section class="container section compact"><div class="contact-bottom"><div><h2>Prefer to explore first?</h2><p>The curriculum is open to everyone, with no account needed.</p></div>${link('/curriculum/', 'Explore the curriculum')}${link('/faq/', 'Read the FAQs')}</div></section>`;
}

export const pages = [
  { path: '/', title: 'Thoughtful chess learning', description: 'Explore NX Chess, a chess teaching center. Discover learning pathways, the curriculum, and ways to contact the team.', render: home },
  { path: '/programs/', title: 'Programs', description: 'Explore proposed NX Chess learning pathways, from chess foundations to guided game review.', render: programsPage },
  { path: '/curriculum/', title: 'Curriculum', description: 'Explore five proposed stages of chess learning, with topics, practice examples, and learning outcomes.', render: curriculumPage },
  { path: '/coaches/', title: 'Coaches', description: 'Learn about the teaching approach at NX Chess and ask about coach introductions.', render: coachesPage },
  { path: '/about/', title: 'About NX Chess', description: 'Discover the idea and learning approach behind NX Chess, a professional chess teaching center.', render: aboutPage },
  { path: '/faq/', title: 'Frequently asked questions', description: 'Answers about exploring the NX Chess curriculum, getting started, and asking about lessons.', render: faqPage },
  { path: '/contact/', title: 'Contact NX Chess', description: 'Reach NX Chess on WhatsApp at +971 55 767 8025 to ask about chess learning and the curriculum.', render: contactPage },
];

export function document(page, origin = '') {
  const canonical = origin ? `${origin}${page.path}` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)} | NX Chess</title><meta name="description" content="${escape(page.description)}"><meta name="robots" content="${site.preview ? 'noindex,nofollow' : 'index,follow'}"><meta name="theme-color" content="#244c3a"><meta property="og:type" content="website"><meta property="og:site_name" content="NX Chess"><meta property="og:title" content="${escape(page.title)} | NX Chess"><meta property="og:description" content="${escape(page.description)}">${canonical ? `<link rel="canonical" href="${escape(canonical)}"><meta property="og:url" content="${escape(canonical)}">` : ''}<link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><script src="/site.js" defer></script><script src="/motion.js" defer></script></head><body>${header(page.path)}<main id="main" tabindex="-1">${page.render()}</main>${footer()}</body></html>`;
}

export const notFound = { path: '/404/', title: 'Page not found', description: 'Find your way back to NX Chess.', render: () => `<section class="container not-found">${badge('404 / A MOVE OFF THE BOARD')}<h1>Let’s find<br><em>your way back.</em></h1><p>This page doesn’t exist. The curriculum or homepage is a good place to start.</p><div class="actions">${link('/', 'Back to home', 'button')}${link('/curriculum/', 'Explore the curriculum')}</div></section>` };
